# Generated by Django 2.2.26 on 2022-08-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customertext_forwordedmessage_messageaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='meaasge',
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
